main :: IO ()
main = do
  print . head . filter root . concatMap (\x -> [x, negate x]) $ [0..]

root :: Integer -> Bool
jqnt x = pbvp x * rlcg x
zpmp x = mzgv x - mbfh x
jshn x = mrmn x * hjbv x
mgml _ = 7
zcsd _ = 9
wlqf _ = 5
znrf x = thnv x * qzwq x
gnqr _ = 2
wldr x = plzt x * ltnt x
dzfv x = ljrb x * trgh x
qvqm _ = 4
rzmj x = vbrp x * mplp x
wzvq _ = 3
qrhm _ = 4
scrr _ = 2
vzvf _ = 5
hmfn x = gnrz x + hsqv x
spgm _ = 6
fdht x = vqgh x `div` vwhr x
nrvq _ = 3
pcft _ = 2
pjfr _ = 3
lcnp _ = 4
nrzq x = llsb x + wndm x
ftmm _ = 3
jtbs x = bcbj x * pwjt x
ntdw _ = 5
szzc _ = 3
vszp x = wpft x + dwlg x
ptrd x = whtw x * jppd x
bswr x = mddt x `div` pflh x
tgcd x = dtht x + htpb x
zfhg _ = 2
slhj _ = 5
hlgf x = zdpq x * pqdm x
qzvr _ = 3
jpqr x = cwsz x * fsgb x
jtzf _ = 1
nbfr x = lpqm x + qrjl x
zqqh _ = 3
wprm x = qvqm x * tnml x
mstv x = rmfv x * lrwq x
mvtz x = tztp x * gzwr x
qdjq _ = 3
dbnb x = wqhd x + zwgn x
hdjc _ = 2
lscf x = wgdt x `div` rszm x
wcrb _ = 2
srhm _ = 5
zpdd x = ddjd x + htqs x
qhgr _ = 2
bbqp _ = 2
nbgg _ = 11
psnh _ = 2
wgpd x = lgtf x * wmns x
cmmc x = npcc x * wlrc x
lpqm x = gbpf x + vdmf x
qtmd _ = 4
rdjs x = zltc x + nnjc x
szhl _ = 4
hfzv _ = 2
rpqd x = tthn x * nzdd x
tcch _ = 15
hctr x = clmw x * czbf x
jrpq x = lwsh x - tjsw x
fhbl _ = 3
wmvp x = gzfw x * ltzs x
hlmb x = jzqn x + hltb x
vvnb _ = 14
pgbl _ = 2
tcmv x = jqqp x * vsbr x
cflj x = qtqs x + ldmc x
wlgr _ = 2
brpw x = jqgn x * ssqd x
pgnm x = nnmc x - rzcw x
mrhs x = zgpv x * nqfz x
wnjt _ = 2
hdpd _ = 17
dpcn x = gwwg x * gtqs x
grtg x = cbbw x * vcpp x
jgsm _ = 7
frsj _ = 6
lrvs _ = 1
rvfg _ = 17
fzrr _ = 2
tzlm _ = 17
qcwh _ = 7
tdbj x = gtzc x + ztvj x
mlmh _ = 2
jzqn _ = 2
gwrm x = mwzq x - wwdn x
vhtg _ = 2
nlrl _ = 12
lcgh x = zrpt x * mstv x
bfgn x = lqhf x * tjrq x
jzzl _ = 3
hlhr _ = 4
wmnz x = qlmt x + zvln x
hqvc _ = 4
root x = lrnp x == ptnb x
rddv x = smtv x * cgbl x
qptw x = lgfr x * hthv x
hshb x = dztm x * tftn x
tcvc _ = 2
qwzn x = gjrp x + ccrc x
bbsb x = prcf x * fwcn x
cmtm _ = 4
sffw _ = 3
brcp x = srcb x + srhz x
nvwn x = pczb x * fcgf x
zwsf _ = 2
slwc _ = 5
jmnq x = hsct x + wvmh x
fjjh _ = 9
hmpc x = cdfw x `div` shzq x
cbbm _ = 2
nvlw x = dssp x * mtpw x
ndrm x = tqcn x * qdjq x
gvln _ = 13
rqbr x = zcsd x * rbst x
nqgm _ = 3
qfgd x = zthn x + jrsf x
cphf x = dsjl x + qnqg x
mdcp _ = 3
humn x = x
mtnn x = ggbq x * pqvv x
zzcn _ = 5
hmnl x = nsqm x + hzmt x
bntv x = nmcn x * rffb x
wclm _ = 2
dszs x = gbhg x - dldg x
slnn _ = 1
qhcb _ = 6
wtnl _ = 15
hrpd _ = 3
dldg x = cbff x + dcdz x
nsqm _ = 7
dzsc _ = 2
dffm x = jnzj x + dbdb x
bnhf x = slfr x * mnbc x
gzfw _ = 4
mpwv _ = 5
vqng x = vlsm x * ldvh x
cwqz x = qwqv x + mgtm x
rhmr x = jttn x + lfsn x
znqr x = pmqv x * ftdc x
jmvf x = nvbp x + fvdz x
spgl _ = 14
wzrg _ = 2
bctt x = lfft x * vghr x
cfhv _ = 5
glsv x = wtms x * qcwh x
djmd x = tdbj x `div` pdrr x
vlcv _ = 2
bbbv _ = 2
zcnv _ = 5
phwr _ = 4
bgnn _ = 3
fngm _ = 5
tdhg _ = 2
mfrt x = nmcj x * smth x
vvjt _ = 2
wtth x = cghj x * jftm x
htmg _ = 3
bqfs _ = 2
thwb x = tjjd x - zfmz x
lcmr x = lqjw x * tdhg x
hqrf x = wczc x * hdhm x
gjsn x = vbch x * plvv x
fbcs x = ggpz x + lczf x
nbdp x = pzdh x `div` cnwv x
jgts x = vnlp x * vpvl x
sdws x = zzdv x * qvnh x
ptmp x = pqcs x * rhpv x
jllc _ = 2
thjv _ = 2
hwwf _ = 13
tjcs x = sgnc x `div` jgmf x
ntpt x = tfpj x + hddp x
fztc x = cjzq x * lmpw x
bnhm _ = 19
gvrc x = mnhd x + hgfb x
mclb x = nvwn x `div` lpnc x
nzjb _ = 3
jvzh _ = 14
zzrj _ = 2
vwlz x = ctgv x + wbbg x
qhvd _ = 6
rzsc _ = 2
vbjj _ = 2
hssg x = vgnr x * zlcm x
grmj _ = 2
brwt _ = 5
snmv _ = 2
czqz x = jvzh x * wlgr x
hfdd _ = 16
pzvd x = fdht x * qnff x
qzfs _ = 2
twfq _ = 2
qpmr _ = 4
jtrw x = hqzs x + vllt x
frnj x = cfzt x + hqrf x
swmw _ = 2
vsbr x = tvls x + lnln x
gpzv x = gbth x * rqqq x
tmqv x = sflq x `div` gznf x
ztpb _ = 10
fcpf _ = 5
gqmc _ = 2
pclz x = swmw x + cqjh x
tvls x = blsf x + mppt x
tqqg x = jllc x * hfbm x
vghr x = wgcp x - ptwq x
vhwt _ = 4
wrrz x = dmlp x + cljf x
sfdw x = rfwl x + tlcc x
frjw _ = 3
wjsm x = wbvb x + pqss x
sjgs _ = 5
rlfl x = ngmb x * lftp x
ghmc _ = 5
qzwq _ = 8
bljh x = flwl x * qghl x
qpbd _ = 5
fbjf x = gpwc x + hlhr x
cccf _ = 3
jlqz x = tpml x + ljzh x
qhjl x = hmng x * trpn x
rfgs _ = 17
thzt _ = 1
rrrt _ = 7
fpdw _ = 4
qnhg x = tsgz x + lcmr x
ndhs _ = 3
pndg _ = 4
rsql x = nctz x + qjhd x
wrvc x = jlmg x + lcgh x
pfdc x = cpwt x + smrs x
btnp x = wzvq x * lrmb x
wsgg _ = 8
zlgl x = dbmb x * bswr x
crnr x = nqgm x * fcfp x
dtgz _ = 18
pvbq _ = 3
ztgj _ = 7
vbrp _ = 2
qvgd _ = 6
lftp _ = 4
stsg _ = 16
hthv x = tlbq x * mfrt x
jrwl x = cvnm x * lrgg x
tsgw _ = 1
wmns _ = 5
lpnc x = wpmb x + bbqp x
tthb x = sgmj x + qfjb x
znbv x = tcrq x + nftj x
hssj _ = 2
bbtv _ = 2
clcs x = psbl x - snbg x
gznf _ = 2
stlw x = vllg x * sgzd x
nrfc x = fbcs x + nrqm x
bzwm _ = 5
flfb _ = 2
rtmr x = cqmt x * qfrq x
zwgn _ = 2
cvjp _ = 8
vlgp _ = 5
qbhr _ = 1
zqzc _ = 5
svbz x = sdbs x + gnlv x
svjd x = zzcn x + nhlh x
hclc _ = 2
bslr x = plmf x * vhps x
qrjp _ = 9
zdtr x = rtmr x + fsnm x
sgcb _ = 4
zddf _ = 3
cqlc x = nrzq x - qjvj x
fhbb x = tzwr x + lzbs x
gjvp _ = 4
qbhp x = cfpw x + tjww x
fmjq _ = 2
gqnc _ = 17
cwzb _ = 3
lgfr _ = 4
sjfw _ = 1
vhmn x = nzdc x + fncj x
mdpr _ = 2
frrv x = wvmc x + zrrl x
dvrh _ = 2
lwhn x = tcvc x + bvrg x
tpfh x = fzzz x + bmng x
gpsz x = pcvq x * mgpz x
zmvr x = qcbz x * pcft x
bmqf x = cmnn x * fvgd x
zrzd _ = 3
wfjl x = llmh x `div` dcgw x
grzd _ = 1
cfmc _ = 15
cqmt _ = 4
tztv _ = 3
rfbd x = mrsr x + jvbh x
smvs x = fspg x + stsd x
cnwv _ = 2
brzz _ = 3
dzfb _ = 3
wssl _ = 3
rrql _ = 15
wzwj _ = 2
dmlp _ = 15
qsfj x = rmvw x * hdjc x
vhtt x = hwzc x + rlfn x
gtfq _ = 3
wwwq x = svnq x + wvts x
qfrq x = ntgw x * tlvz x
tpjs _ = 2
mtgs x = sthg x + gndt x
npcl _ = 6
mjgm _ = 3
tnml _ = 2
bmzt x = gvrz x + mdst x
dvgp x = rtnq x * qjlv x
jjgm _ = 3
sqpm _ = 7
tqcn _ = 5
glfv _ = 7
ppgn x = nngr x + mvvm x
zjqt _ = 8
zwrt _ = 5
rsth x = tqfr x * lnff x
grrn _ = 2
vznv _ = 5
cfzt x = gpsz x + cfhv x
qjmn _ = 3
nnjc x = lnng x * grnt x
hzwl x = rldm x * tdlh x
jsps _ = 2
rhpv _ = 4
ltnt x = svjd x * qhhw x
fvqs _ = 2
zqrj _ = 3
ndbv _ = 5
rfwl _ = 5
qdqw x = btsh x * jdsj x
htqs x = slnn x + dtzb x
jttn x = mthp x `div` psnh x
mjlp _ = 17
vzjm x = bntv x `div` gjcz x
bjjp x = frrp x * hgjs x
ghsc _ = 2
mlhm _ = 10
pqvv _ = 8
vlsm _ = 2
wjbl x = cllj x + vtrq x
twdv x = cwsg x * gpnm x
fsjt x = tcmv x `div` zbbb x
vwrn _ = 1
jbrt x = dggc x + vpfg x
jlrw _ = 1
jvfw _ = 5
gjrp x = vnzb x * npcl x
jrsf x = vplh x * zzzf x
hgqd _ = 2
ptnb x = jbmb x * rlvm x
lphv _ = 11
mrdl _ = 4
gpdc _ = 2
qjvj _ = 14
grpp x = fzjc x + wbmb x
gbwq _ = 3
bptt x = vscv x * prsb x
cvfr x = mcwm x * ztgj x
mmvt _ = 17
gjwp _ = 8
zvrq x = tssd x * jwhh x
mtrw x = fmvl x * qcbd x
ghnr _ = 5
prhr _ = 10
gsfh x = hctr x - vlcv x
vhwj _ = 4
ntrl x = nprf x `div` vggv x
shwg _ = 2
jwlh _ = 3
glhp _ = 2
pcqp _ = 2
bvvn _ = 2
mddt x = pggh x * mjpt x
zndj x = smmb x * qwzn x
pflh _ = 2
zspt _ = 2
thnm _ = 18
jwhh _ = 2
sjhj x = jgts x + bnfz x
sflq x = spwn x * dffm x
qflw x = pntb x + jvqr x
zppq x = tmzv x * nvdr x
qsww _ = 2
zltc _ = 2
hvnc x = stsg x * tjld x
dwwq x = tcsw x * thjv x
jpgc x = hwsj x + twdv x
cfql _ = 5
mgpz x = mgml x + cwqz x
rcdl _ = 4
tvmr x = wrbm x * sscj x
dnsm x = pbdn x * hbvz x
ntcw _ = 13
vfgr _ = 4
qpcs _ = 3
qcbd _ = 2
nqzw x = lwlj x * wlpf x
vhvw x = pzls x + dmnh x
dsph x = npjd x * czdc x
mctw x = rcdl x + hpft x
hqcz _ = 13
rzzv _ = 4
ntbt x = jzbh x + vfcg x
dsjl _ = 8
sfqj x = nntl x * mdpg x
vnps _ = 2
vcpp x = nrjw x + szgs x
cgnv _ = 7
cqbc _ = 9
qddg x = tgcd x * hssj x
tszn x = rrzp x * vznp x
rsvn x = bqdf x * wfcq x
ncjm x = rdsr x + dlcl x
mssp x = sffw x * fprq x
ptnl x = rsth x + dvfs x
pzls x = dbnb x - bzsl x
bdmn x = bfgn x * hngg x
vjnb x = qmff x `div` shhz x
ghql x = hfzv x * tjzq x
ldht _ = 2
dfdf x = rmsm x `div` mqps x
ttvq _ = 2
bqfp x = dnhj x * qcsz x
dfss _ = 1
lrwq x = pprq x `div` gnqv x
zdpq _ = 2
clmh _ = 4
nhsv _ = 2
hltb _ = 7
nnwz _ = 2
vnlp _ = 2
jtcc _ = 3
smtv x = csqd x * dzlg x
tczp x = pptc x * wfzp x
drqv x = zfqj x + zssv x
fnbq x = hvdb x + pctt x
dmnh _ = 12
zbbb _ = 4
jnfn x = dzfv x + lrvh x
gjfn x = pvjv x + sscm x
zwzf _ = 3
jqhl _ = 2
phbd x = pndg x * lgbt x
jqnr _ = 5
prng x = wtwf x + gwct x
gwrt x = bggd x + vnpf x
tnlv x = hngq x + mwgz x
rldm x = qpcw x + jhqt x
dlqb _ = 3
zvsl _ = 2
hcds x = qtjh x - scdz x
tfgf x = szzc x * zgjr x
wdch x = wlbg x + hshb x
lngj x = tmqv x * qvlg x
dcgd _ = 2
hdhm _ = 5
zfqt x = zppj x * rzsc x
rrnr _ = 4
mjwg x = znbv x * bczm x
nggq x = gqmc x + srhm x
rfgf _ = 4
cwsg x = sbpm x + bvwp x
rmvw x = pnvl x - pgdz x
zhdt x = nmvd x * phwr x
trcf x = gffz x `div` lgzn x
snss _ = 2
clhd _ = 7
swjj _ = 6
ztcz x = mqhh x * zmdb x
nzln _ = 5
wgdt x = jvzm x - czss x
rmwv x = gllg x + bglf x
bqdf x = llrz x * jcjv x
qjhj _ = 17
bpfw x = rrnr x * tzwq x
dhgt x = snss x * phlv x
hmtf _ = 3
shpb x = szhl x * zqzc x
rbls x = lrml x + vgsn x
sscm x = nlrf x * nnhw x
srhz x = bgtl x * zcsh x
lfpq _ = 5
thzh _ = 5
ljrb _ = 3
mwjz _ = 4
htfg x = hjrg x * dvrh x
dpjr _ = 16
wvcj _ = 5
zqsq _ = 15
wmtr _ = 9
zqbr _ = 1
gmvv _ = 9
fnvf x = sfsl x * lrlr x
dzlg _ = 3
lqps x = mjqw x * glpq x
bjqt _ = 3
hctg x = nfzq x - psfm x
gsng _ = 2
fdnc x = cvtj x + pcmv x
thtq _ = 3
rfcl x = mbcn x * drnf x
gpcm x = qhgr x * cjgz x
fbgv x = zgjz x - czqz x
vcdw x = csdz x + ssqm x
zbwr x = tlmc x * hmmg x
zrqz _ = 18
fvgd _ = 10
vbpt x = zndj x + hppf x
wnqt x = dfrv x * wclm x
pqll _ = 3
qvmc _ = 3
zcdm _ = 3
wqhm _ = 3
hvbq _ = 3
gcrz _ = 2
mhgf x = tpfh x * wlqf x
lrfl _ = 6
tssd _ = 4
qghl _ = 2
hbdn _ = 4
zlhc x = pvzh x * rjgs x
mlrc _ = 4
ddfg x = fmjq x * tbht x
hbgj _ = 2
gctz _ = 2
zjtq _ = 2
qjhd _ = 17
lwvt _ = 4
nqfz _ = 2
dtrc x = zpzl x * dbcj x
pnrc _ = 3
hpqn x = vqng x - lctz x
wvbs x = wbwc x `div` rwzn x
bgmw _ = 5
nfwg x = ftrn x + hnmt x
qwgl x = qppm x `div` nglv x
mplp x = dnzc x * brzf x
vqnv _ = 14
tbht x = dtgz x + srln x
jbpl x = mnzr x * vhtg x
lcsb _ = 6
smmb _ = 5
mgdt x = qgfj x * snmv x
szcp _ = 3
ntgs _ = 2
gqdr x = rlfl x * wljs x
svnq x = chdq x - hvbq x
bmhm x = ccmn x * cjtr x
gqjp _ = 4
qsmj _ = 8
qdnf x = zqqh x * bjqt x
zgvs x = bfvn x * mrqv x
gwqm x = mtnn x + fvtm x
wcwr x = mngm x * wjpt x
wfnh x = fhlz x * hjpw x
cjwl _ = 2
sswt _ = 2
jpsj _ = 5
jwpj x = zmvg x * fjjh x
whzd x = vhwt x * dmgh x
bhwr x = pjgr x + fccw x
bhlg x = qchf x + pjht x
mnds _ = 3
bhbt x = jshn x * mssp x
tcdc x = brcp x * hdpg x
hscr x = cvbz x + mrjd x
njnm x = pdjn x * hzdp x
zczf _ = 3
jqqp _ = 4
rsjt _ = 2
lqvc _ = 6
hmvr x = bmjf x * httj x
tpqn _ = 12
cmcz x = zzth x * zjvq x
lwqc x = cfvf x * gtvq x
vlqj x = tnsd x + zqsq x
nprf x = rzmj x `div` fcrg x
nztd x = wffd x + ltfr x
bfqw _ = 5
lwcn _ = 4
qdcb _ = 5
lgbt x = hvnc x `div` hcbq x
srcb _ = 18
qsfc x = jpwc x * vltp x
qhhw x = qjmn x * gvzl x
vpwt x = hfcq x `div` zbwr x
tjzq x = zphm x * pqll x
pvss _ = 2
sqrg x = hlcv x `div` jbzb x
jchm _ = 5
lrnp x = gdgf x `div` mnqw x
nbsm _ = 5
rmsm x = rhct x * tzlm x
plds x = wvgc x + rrql x
pcmn x = wsgc x * drqv x
drmn _ = 2
frjn x = mbjt x * hzng x
mnqw _ = 4
mfpl _ = 5
hghv _ = 3
tjsw x = dfwf x * mtwm x
rsrf _ = 4
vggv _ = 5
nnmc x = gpsr x `div` mlmh x
mthp _ = 18
dgtm x = pvjr x * qddg x
sljv x = vwfd x `div` zzrj x
cllj x = chvn x * thvd x
zrsh x = fwdd x `div` dftr x
ljlt x = rvdn x + wrrs x
fhwn x = vlqj x + hfhc x
cvbz x = wnfq x * nndj x
mvnd x = spcw x + rhqz x
jsjt _ = 8
ldmc x = pdqv x * gsfh x
vqvj _ = 2
zphm x = jbfl x `div` vnfj x
lzdq _ = 3
gjcz _ = 3
zcpl _ = 9
gwfz x = tssj x + cqrg x
wbbh x = jrwl x - fhgb x
hfjf _ = 3
lqtl _ = 5
fcbp x = tbmq x * qdcb x
clrn _ = 2
mvzq x = rcgn x * jqnj x
mbwc x = bjjp x + hbgf x
nntl _ = 3
vnll _ = 4
llbz _ = 4
rdvv x = fntl x + hwwq x
crsz _ = 5
mccf _ = 3
lfvc x = jsln x * fvhj x
dcfg _ = 4
gmlz x = jwlh x * rsjt x
tnbf x = gwfz x * lwvt x
thhw x = qrhm x + fdlw x
zgjz x = vtpj x + spzs x
gdgd _ = 5
ltzs x = zwjl x - cbds x
lsmq x = ndtf x + qdqw x
hppf x = sljv x * bvvn x
znhc x = znrf x + nwlz x
mwhg x = sbqb x * dlgr x
gcgf x = lzrv x * rhng x
dgcw x = rvmb x + hjtp x
fwdd _ = 12
vswn x = spgm x + wgth x
ssqd x = mbpj x * wzrg x
cztd _ = 2
njjj _ = 2
qfsq _ = 2
rcfj x = dtwf x * cgnv x
tlbq _ = 2
mqwg x = dlgp x - zqbr x
zzsm _ = 3
tsmg _ = 3
ptww _ = 2
tczq x = fztc x - gvmp x
dztn x = tnbf x + humn x
jvzm x = hsmq x * fhwn x
qcrd x = gwqm x * qhvd x
bvrg _ = 5
wlsb x = ntlb x - zjbz x
mwlw x = ffnw x + tbgt x
stff _ = 5
csdz x = nbdp x + dlbc x
hsct x = gflj x + qptw x
zbct _ = 2
chhw x = nrsl x * gdgd x
ptmz _ = 9
vvvj _ = 3
tzwn x = zfcd x * qvmc x
chht x = cbjr x * ntgs x
rlfb x = mhrs x * mwcn x
dqrm x = vhmn x * gvfl x
czdc _ = 2
vbwt _ = 1
nmnp x = qtfw x + vmqs x
hdht _ = 3
jwfc x = bhwr x + mzpc x
wqhd x = cqrn x * lwhn x
dzcz _ = 14
qmlp _ = 2
pjmc x = bdjr x * mjzz x
lzwl x = wmnz x * wcsd x
jtsc x = vjhh x - fwbl x
fvcm x = hcds x * hwwf x
hjnc _ = 3
tptd x = plwg x * gcrr x
grbh x = qwzz x * tqnb x
tpdw x = pcmn x + hdmr x
fgqr x = jgsm x * hdpd x
hzdp _ = 2
mbjt _ = 7
fnsf x = rdjq x + grpp x
nzmw x = thtq x + crpb x
ncfg x = wzgj x * tpjs x
vqfp x = csvj x * nftr x
mfvj x = hvhl x * hgfj x
gpnm x = ghnr x * lqvc x
wlrc _ = 2
lswp _ = 5
ggbf _ = 8
lrml _ = 8
qvmm _ = 6
vfcg _ = 1
hggv _ = 4
qnvw x = ghws x + btnp x
rdtv _ = 2
tzwr x = zwzf x * ltpq x
cggh x = jtbs x + ndpl x
mlfm x = qhrf x * ghsc x
lzdh _ = 1
flwl x = ngmp x * mctw x
dztm _ = 9
gjpr _ = 11
gghl _ = 5
hrqj _ = 3
rpgs x = wdch x + fwjs x
ndgg _ = 17
fgdn x = qnhv x * dszw x
gcgl _ = 9
dbvs x = rrsz x * vwfs x
smrs x = hmnl x * cfph x
vpfg x = zmvr x + zppq x
lqhf x = dvbv x * hbgj x
dczz _ = 3
jzct x = cztd x * hlcg x
pwhz x = vrcm x + pzvv x
trth _ = 2
sqwq x = pqnp x + jmnq x
vzgg x = clcs x - gwrt x
tvzt _ = 6
vpct x = rlfb x + vzzw x
nzgw x = gwfr x + nllh x
jtgr x = gmff x + hmtf x
fdlw _ = 3
vtpj x = fsjt x + rstc x
rtnv _ = 9
lgcn x = bjrp x * bgtd x
wsgc x = ftmm x + jvhl x
gnwj _ = 7
fprq x = wssl x * tnmp x
lnvz x = fhbl x * hdht x
gmff _ = 4
dcmz _ = 3
cqbh _ = 3
pqdm x = gjsn x - zplv x
vdhh _ = 2
tdts _ = 4
glpq x = vnll x * ffww x
bbgg x = sbdc x + qdvf x
gzbl x = rsqs x - cjql x
mjpt _ = 2
jmdq _ = 4
rhdt _ = 2
hbzb _ = 14
hmmq x = tbgd x + ddfg x
csds _ = 9
cvcd x = ntdv x + hjqn x
rlcg _ = 17
jrps _ = 14
nnhw x = mldt x * zqfl x
svht _ = 12
pbdn _ = 3
llpn x = zrqz x - lfrc x
lpqq _ = 6
fjbp _ = 2
tngj x = fprc x + qmbr x
cjzq _ = 3
dwch _ = 4
psbl x = bcfl x * tsws x
mvqj x = bqgv x + qprf x
rjgs _ = 19
nlrf _ = 4
qrjd _ = 4
vccf _ = 3
dwjd _ = 18
pdcz _ = 11
cbds _ = 4
drbf _ = 2
zldl x = sfdw x + lrvs x
tmmr x = jtzf x + bcwc x
gvnd _ = 2
sgpb _ = 13
zbsc _ = 13
cdfw x = nwqg x * zrsh x
jbfl x = shtg x `div` sjrq x
mrvc x = lmfh x + jjrc x
pstg x = gbwq x * pzfd x
mwzq x = gzbl x * dzsc x
ggdc x = ljlt x + dclh x
ghjz _ = 3
pcmv _ = 4
tpcd x = svdd x * dwzp x
mnbf x = cbbm x * vhsv x
cfph _ = 2
qprf x = wmnt x * flnr x
qdnr x = pwhz x + cczr x
mwjp x = fhzf x + rhtm x
lzfr x = zvsl x * ncdt x
vnss _ = 2
hfhc x = mffb x * lzfr x
pftl _ = 4
pjgr x = lhnn x + wdjs x
mgtm _ = 1
nzsf x = wncm x * bssq x
rlsm x = jqtn x + llbz x
wznb x = wqdj x * qggh x
jhnn _ = 7
vhsv x = njss x + jsjt x
slqz x = hdsh x `div` wzwj x
hwsj x = thfl x + qmln x
rrsz _ = 5
zqfl _ = 3
jnpb x = qsjm x * gngt x
rcgn _ = 16
gndt _ = 1
dlcl x = ddfd x * csds x
bwjb _ = 1
wvch _ = 9
tftj _ = 19
ltfr _ = 3
tqgd _ = 2
vscv x = lndr x + vmwr x
hnrv _ = 3
pqzh x = vcqv x + tpdw x
cgbl _ = 5
hngg x = dczz x + ttzn x
mlqh x = frsj x * tsmr x
nlnc x = pcjh x * vbwp x
mrqv _ = 2
fzzz x = vvjt x * bznr x
wzzt _ = 2
frrp _ = 2
wjlt x = jvzj x * wvcj x
gllg _ = 12
nftr _ = 4
zbdh _ = 3
shtg x = nrtn x * pstg x
rjvz _ = 4
nwqg x = vjcw x * mghs x
cghj _ = 2
lpbc x = vvnb x + jjnp x
vzsj _ = 3
cvhp x = gjdv x * cmlh x
fczq _ = 3
pqcf _ = 2
mfvg x = ngmr x + djcd x
vdfl _ = 5
zwjp _ = 5
jgzn _ = 4
sfzt _ = 3
qgfj x = bmhm x `div` hrmz x
dfwf _ = 5
jmhp x = wpcg x - jpzq x
tzjn x = vnss x + lrdr x
tjpq _ = 3
wvtf _ = 4
nptp _ = 2
gtjq _ = 2
smlf x = hqcz x * rrrt x
mfdl x = csts x * jvpf x
nvzc x = pgbl x * zmwz x
jjnp x = jwrv x * dzfb x
qrjl _ = 1
gvfl _ = 2
hsqv x = wwmt x `div` zwsb x
gfbl _ = 4
hjtp x = pzvd x + vccm x
chvn _ = 2
jftm _ = 4
mtpw _ = 5
gpgc x = jpgc x - swbf x
ttpj _ = 3
tcsw _ = 5
bzgj x = lggn x * jprn x
hwzc _ = 3
zzlb _ = 2
jttv x = pnrc x * rdjs x
ngmp _ = 2
qhtj _ = 2
gwnd _ = 2
jndw x = nwvc x + ffvp x
ntgw _ = 2
ncdt _ = 3
cqrg x = tcvm x * cmtm x
gwhl x = bfqw x + hsbz x
hnrt _ = 2
mdhm x = htwl x `div` mbhn x
rlgf _ = 2
prpt x = vdqc x `div` glqc x
mhrs _ = 2
zwfh x = tvqt x - wjbv x
qngt _ = 5
vllt x = hzwl x `div` pmzc x
rqrd x = rpgq x `div` grtw x
wncm _ = 9
cwvh _ = 2
qwzz _ = 2
dmbc _ = 2
hbcf x = zfcp x * vcdw x
wwnw x = zlhc x - dfpv x
cbcn x = lfbg x `div` msfn x
hjbv _ = 2
hfwd _ = 8
plzt x = hnrv x * brzz x
hnmt _ = 5
nfqb x = gdmr x + cvjp x
lqjw _ = 5
ltmc x = lfpq x * hhjd x
qdlz x = qmwg x * dztn x
swnz x = ghjt x * dgpw x
sgnc x = wmcd x * scbr x
gtzc x = cgcq x `div` stff x
csjl x = hbzb x - ndrr x
gmmw _ = 4
ddzl _ = 3
vmpw x = nbdg x `div` dtqp x
dlrc x = cdhh x * nrvq x
dwpd _ = 3
gfpj x = mvmw x - vdfl x
fcrg _ = 2
dttp _ = 12
qpvc _ = 11
tpbr x = bzwm x + dwjd x
fwcn x = jbrt x * gcrz x
hvzq x = gqds x * mhbn x
zbzh x = qflw x + qqcl x
tddb _ = 2
nglv _ = 2
btsh _ = 3
ndbs _ = 4
rdsr x = rsql x * mjgm x
rjvr x = qtbs x * ljsl x
hddp x = hzsg x `div` qmbg x
wrrs x = wprm x + grrn x
rhng _ = 2
wfzp x = pdbq x * fnvm x
lfbg x = fvcm x + zrpq x
vpsh _ = 4
ldlh x = wwnw x * qljf x
dfrv _ = 4
tjld _ = 5
mdst x = gvhc x * gctz x
cbvr x = ltmc x * lljs x
hvhl _ = 3
ddjd x = wsdt x + nrqf x
qpns x = jzct x + zgvs x
cljf _ = 4
llgg _ = 11
bpfj _ = 18
hfbm x = cnnq x + fjgd x
ssjd _ = 4
gcns x = zrsz x * dmzq x
pnvl _ = 17
nclq _ = 3
wqdn _ = 8
hgfb x = qrjd x * dvbs x
lctz x = jvnv x + prgt x
drjf x = ggbf x * zjsz x
vrbn _ = 5
jvqr x = mwjz x + qjhj x
lgbp _ = 3
gwns x = dgtm x * mrvc x
nqwj _ = 2
bqgv x = cfms x + vfjc x
qlmt _ = 1
wvpp _ = 3
jjhz _ = 3
zjnf x = ffbh x + jbrc x
hqnt _ = 3
rbst _ = 4
jrjz x = sdff x `div` wfjz x
qvlg _ = 5
chzp _ = 2
wpmb _ = 5
wtwf x = pcqp x * jltf x
qmgw _ = 19
tpcb _ = 4
zfwc _ = 7
gwwg x = qcjf x + tndg x
cqjh x = lphv x * qljz x
twth x = llgg x + jghl x
tftn x = wmvp x + zcpl x
djcd x = dpjr x * tqgd x
gqdg x = lfrp x + lrzf x
tccg _ = 13
wrqj _ = 4
wljs _ = 2
nmqc x = bpfw x * tdts x
vccm x = sljs x * qwbh x
ztvj x = nvzc x `div` mlqv x
vjhh x = pfdc x * tvmr x
jqtn _ = 5
fsrr _ = 5
jsln x = rczv x + dvvz x
mzpc x = wldr x `div` fccc x
nrfj _ = 2
smcn x = gsng x * lcfr x
vldt _ = 2
lpmr x = mbwc x + fvcj x
zlsn x = zvfc x + jhnn x
cjtr _ = 2
zrpq x = tzjr x * vdhh x
wfcq _ = 7
mffb _ = 3
nbdv _ = 4
cldt _ = 2
hjpw x = hcng x * zczf x
pprq x = jjmj x * gnwj x
glwz _ = 2
mrmn _ = 3
vmqs x = fdnc x + cmmc x
vwwm _ = 4
rvdn _ = 5
glqc _ = 3
rstc x = rvdb x * gtfq x
mzdh x = grlr x * lvqs x
jgrn _ = 2
pqnp x = prdj x * sgfm x
sbpm _ = 4
nmvd _ = 2
trrs _ = 2
ljfg x = mwhg x - cmmv x
zhsh x = gqjh x + shzd x
tcmm _ = 2
zzth x = hfwd x + mwlw x
htwl x = wbhn x + lghq x
fmmm x = whtc x * jqnr x
fccc _ = 4
fntl x = dvqw x + tcdc x
tlvh x = bbsb x * qsfc x
ztnn _ = 3
llsb _ = 11
qnff _ = 5
gpsr x = rgfb x + twth x
hgfj x = bznh x + wgpd x
fvdz _ = 4
njmn x = vmnd x + wcsf x
bjrp _ = 4
jvpf x = zhsh x - gwns x
sqts _ = 5
lfft x = mpfc x + czbp x
cjql x = gvnd x * mjmb x
lwnz _ = 2
dvvz _ = 19
lqvf x = dttp x + mtcj x
ghjt x = bgnn x * whwg x
wbtp _ = 12
gnhf _ = 3
mzgv x = hpvb x * dszs x
lbdb _ = 5
pqcs _ = 4
wcsf x = bhbt x - gqdr x
dlgr _ = 2
jdhs x = vmzp x + jfrj x
zfmz _ = 3
lbpj _ = 5
ddsg x = lmpm x + dwwq x
lfmr _ = 11
cdsd x = gqnc x * dfgr x
jdsj _ = 5
gwvv x = wqdd x + sjhj x
nvbq x = blct x * nqwj x
jfpw x = thrs x + fgpj x
szbh _ = 3
swrv x = zswv x * pssz x
wrbm _ = 3
hbzf x = mzcz x * mtgs x
mqbn x = rjrr x * fpdw x
plcn _ = 2
lndr _ = 20
hmzr _ = 5
wbbg x = bctt x + vlpt x
dclh x = dgwg x * nfmn x
drnf x = ghql x + mdhm x
tzjr x = phcs x - wfnh x
wjpm x = fcbp x - rdnm x
cvtj x = dpdl x * wtmr x
cmlh x = wcwr x - zzsm x
nggl x = lnrs x + fsrr x
hqgb _ = 2
tlgn x = vzgg x * slwc x
pgmm _ = 5
qcqj _ = 1
vnfj _ = 6
vghw x = wnqt x + mlrc x
sgph _ = 5
mtdb _ = 5
pltr _ = 18
rswh x = pvqp x + dfpr x
zthn _ = 3
zvln x = hnbl x `div` gnqr x
mgmt x = gfwc x `div` hmmm x
qplc x = mgvl x * tqtv x
tqhv _ = 11
snnv _ = 5
jprn _ = 5
tfpj x = cmcz x `div` ntbt x
rjcb _ = 10
lljs _ = 8
dwqm x = zgpl x + lwqc x
wgcp _ = 13
qrbc x = tczq x + wtnl x
rfpn _ = 3
psnd _ = 13
ngmr x = ptzw x * rfpn x
httj x = mffh x `div` jmbc x
bznh x = nbwm x `div` gjcg x
zhsp _ = 4
wvmc x = bzff x * cpmh x
btpl _ = 5
ndrr _ = 1
htmq x = lnvz x + dwch x
ntlb x = nztd x + hcmq x
nctz _ = 20
zvwh x = gbfs x * ndhs x
tjpn x = hssg x * ngjt x
rprs x = tftj x * bdzz x
vnpf x = vwlz x `div` hsps x
trgh x = rtnv x + vmpw x
nfzq x = mjlp x * vvvj x
sdht _ = 2
gffz x = mwsl x + sqwq x
mldt x = mqbn x + qzvr x
nzdd _ = 2
cwlq _ = 3
mghs _ = 5
fcgf _ = 14
wfjz _ = 2
pstf x = nvlw x + nrfc x
qchf x = dcgd x * lwcn x
ldvh x = djmd x - hmvr x
nndt x = hmzr x + prpt x
prjf x = vbwt x + zvwh x
cqrn _ = 4
jjbc x = wvtj x + gztp x
sjrq _ = 5
vjcw _ = 2
mpfc x = rpmw x * qfgd x
hcbq _ = 4
hnfs x = vbmg x * gwvv x
phlv _ = 3
zdhl x = pbgp x * vldt x
csvj _ = 2
gfcp x = hwtj x `div` pqcf x
hbqf _ = 4
bgtl x = fgsf x + szcp x
gtqs _ = 2
rgfb x = fnsf x + trcf x
lrmp x = rshq x + vhvw x
tssj x = jwpj x + dsff x
nsth _ = 2
rvmb x = glfv x * rqjs x
nhlh _ = 1
jbmb x = htmq x * dgbc x
fzbz x = swnz x + gcgf x
wmcd x = qzfs x + hpsg x
prsb x = lbdb x * tjcs x
lzbs _ = 2
bddn x = dtrc x + jpvz x
lfsn _ = 2
tqtv _ = 3
zzzf _ = 2
gqln _ = 2
grlr x = cprd x * nnwz x
dvbv _ = 3
dlgp _ = 8
zgcl _ = 6
pdzt _ = 2
vrcm x = vbjf x + zqrj x
wwdc x = trgc x + dzcz x
wjtq x = zlmw x + clrn x
dzzz x = qvtg x + wwwq x
csdw _ = 9
blct _ = 7
qjwz x = nggl x + mclb x
lghq x = nljp x * rjvz x
pvzh _ = 2
zzbs _ = 3
nrdw _ = 11
bmng x = tdfv x + fjpj x
srln x = jcjn x + tbqd x
zmrj x = cqbh x * gqjl x
cscc x = qswg x * lwnz x
vmrh x = ccmh x * ppgn x
wvtj _ = 1
wdjg _ = 4
qdvf x = zbdh x + nqzw x
bdzz x = gjpr x * brpf x
ndpl x = slhj x * vblq x
fsqh x = zzlb x + msnt x
nwvc x = vqnp x `div` qhtj x
tlvz _ = 4
gvhc _ = 4
lpgn _ = 4
ffnw _ = 8
tvqt x = hbcf x + rdvv x
lnln x = frrl x * vzsj x
zhmg x = gwvh x + mjmv x
vzdd x = brwt x + dvgp x
nngr x = pgjw x `div` mdlg x
jhqv _ = 2
rqzh x = lgqf x + szbh x
tbfz x = bffg x `div` shwg x
zftn _ = 2
fvnl _ = 15
mvnl _ = 13
zplv x = zfqs x `div` sdht x
mnzr _ = 4
rqqq x = zjnf x * fhgz x
zrsz x = tjpq x + sgcb x
cjqs x = tzwn x * wdjg x
lhnn x = prng x + fhbb x
vmnd x = wjtq x * rmwv x
jhqt x = cphf x * znrz x
jvnv x = qhjl x + dsph x
hqzs x = jmdq x * wczp x
clmw _ = 3
ghtr _ = 12
zpzl _ = 5
vcqv x = tfgf x + vrgt x
mbfh x = nmnp x + bdmn x
bltb x = qnvd x * ddsg x
fprc x = qmgw x * lbqs x
vllg _ = 3
cfpw _ = 7
mqps x = hbdn x * vbjj x
lwsh x = vpsh x + phbd x
zzcm _ = 9
rgbn x = svfw x + mvnl x
rclv _ = 5
pwjt _ = 3
hlzd _ = 3
fhdr x = dnsm x * rhwz x
vbwp _ = 2
vplh x = nbgg x * zjtq x
zlcm _ = 5
hbvz _ = 8
mrjd _ = 16
rnqs x = hqsz x - tsgw x
qpcw x = vwwm x + jqgw x
llvc _ = 10
lrlr _ = 3
lwcs _ = 12
vpvl _ = 11
mnbc _ = 4
chdq x = tsvv x `div` hnrt x
gwct _ = 2
wppr _ = 17
dssp _ = 2
cbdc _ = 3
fvqj x = fscs x + gnhf x
vltp x = gffj x + pstf x
pdbq _ = 5
jvhl _ = 4
wsqt _ = 2
zrpt x = jqlz x + zwjp x
dsvv _ = 3
qddm _ = 2
lgqf _ = 4
fjpj x = bltg x * wbbh x
zfmt _ = 5
lnrs _ = 2
fjgd _ = 4
spzs x = qghm x * qvzb x
vbjf _ = 4
tndg x = rhmr x + lcsb x
gngt x = cfql x * qhjd x
nnmp x = gjvp x * bljh x
wdjs x = bjwv x - jjbc x
fsnm _ = 5
wbmb _ = 1
pvph _ = 20
hjqn x = rhdt x * qnvw x
pcns _ = 5
ngpj _ = 6
ftdh _ = 2
msfn _ = 2
mffh x = rnhq x - tmmr x
rvpj x = wrgt x * wbhp x
strt x = zspt x + sgph x
tcqj _ = 2
bvgf x = lpmr x * gqjp x
cpmh x = glhp x * mtdb x
ffvp x = njjj x * zbzh x
hmng _ = 5
ghws _ = 14
thrs x = qhcb x + bnhf x
cgcq x = vfmb x - bbgg x
whtc _ = 2
dcdz x = cjwl x + gmvw x
qnnp _ = 5
mmmn _ = 3
ggbq _ = 2
nftj _ = 4
pvqp _ = 11
ncgt _ = 2
tbqd x = lzth x `div` bhfw x
fhgz _ = 2
wqgh x = jmhp x * lglt x
nllc _ = 7
znpz x = jfpw x + ghmc x
mctz _ = 13
zlmw _ = 17
wtmr _ = 2
hpft x = pvbq x * hrqj x
tnsd _ = 10
tgmt x = gqdg x + wvbs x
wjpt _ = 2
sdtc _ = 14
tqnb _ = 5
hqsz _ = 8
mlqv _ = 2
wwmt x = mfwb x - rpqd x
svff x = qnhg x * vqvj x
qbnz _ = 1
qjlv _ = 4
vbmg _ = 3
gvrz _ = 3
vbsj x = sfpj x `div` rwpn x
cpwt x = fvqs x * jnfn x
dbdb x = dmpn x - wsgg x
lhzs _ = 13
sthg x = lqvf x + jtsl x
vlpt x = pqzm x + zjnq x
fhlz _ = 3
zrww x = bmzt x * glvc x
vzzw x = nzgw x `div` qhgc x
qrwl x = ntcw x * lbzp x
cdql x = nclq x * gmvv x
pvjr _ = 2
jqgw _ = 3
wbhn x = nwpn x * ltjc x
nzdz _ = 8
fccw x = csjl x * dcmz x
vhzt _ = 7
bqbd x = qcqj x + vlrz x
nlvg x = zrww x + vrst x
srlc x = hzfs x * mvnd x
stsd _ = 6
dfgr _ = 2
rzjq _ = 10
mjzz _ = 7
gvzl _ = 2
jvbh x = qsmj x * glwz x
hlcv x = mlqh x `div` wcrb x
bqlr _ = 8
mbrc x = mcqm x * vlgp x
cjsl _ = 4
wgjz _ = 3
wsdt _ = 2
qljf x = ndzr x * fqss x
tbgd x = thzt x + rvql x
pqss _ = 17
whwg _ = 3
hnbd x = sgpb x * jttv x
spwn _ = 2
tnmp _ = 3
hcng x = rgwv x + mctz x
vfmb x = bsjq x * ntpt x
jrdq x = qnqf x * jjhz x
pmlf x = hnbd x + jndw x
rvdb _ = 5
hzrd _ = 6
dfpr _ = 5
bmqm x = dfdq x + gfbl x
gfcl x = ptmz x * sdws x
lflw _ = 2
dnqf _ = 20
hbgf x = vccf x + bqfp x
cbjr x = fbgv x - cztm x
pmzc _ = 4
mhbn _ = 7
dthv _ = 11
bzsl _ = 5
cwtz _ = 3
jjrc x = vwcv x + dfdf x
mjqw _ = 4
jhzw _ = 1
hnlv x = qrwl x * mvfw x
hmgl x = tbbd x * qlrb x
pssz _ = 3
gdgf x = cggh x + zlwm x
tsmr x = nsth x * rclv x
qmff x = gcgl x + ncnp x
qcch _ = 10
nbvg _ = 1
wgvq x = dwbs x + gvrc x
djbj _ = 8
jzbh _ = 6
qhjd _ = 5
pqzm x = jrjz x + bhlg x
vljm x = ghtr x + fhtb x
vlrz _ = 16
nvbp _ = 7
qcsz _ = 5
lczf x = tnlv x * pljb x
jvfq x = rlfd x + tpcb x
hhsz _ = 3
fcfp _ = 5
bvwp x = glsv x `div` jjgm x
scdz x = sjfw x + sfms x
qhgc _ = 4
nlrn _ = 2
lrrg _ = 4
vtrq x = qdnf x + zvdc x
vwfd x = dqrm x + lmjb x
fhtb _ = 11
dtqp _ = 2
wddn _ = 7
lwlj _ = 2
fwjs x = szpw x * pggm x
rgsd x = rfbd x - jsnt x
vwcv _ = 4
prdj _ = 2
drwp _ = 2
szgs x = ggdc x - wjgs x
pctt x = tvzt x * ztcz x
gzwr x = lpnv x + flfb x
vmwr x = mgqm x `div` drwp x
fblh x = qtfv x + hpmj x
gztp _ = 6
lfrc _ = 3
wmnt _ = 3
fhgl _ = 4
cmnn _ = 17
hsmq _ = 6
sclr x = dmhv x + tgmt x
cfms x = pgnm x + bshh x
bhtf x = qdnr x + zjpj x
sgdf _ = 2
hgjs x = lqjd x - wnjt x
hmmg _ = 5
bmjf _ = 9
gfwc x = mmww x * btpl x
lgtf x = bnhm x + vghw x
pvjv x = pdbj x + hlmb x
bffg x = mdpr x * szft x
bdsw _ = 12
znmw x = qqdf x - jtcc x
zmdb _ = 2
pgdz _ = 4
jjmj _ = 2
hfcq x = rfcl x - rgcc x
tbgt _ = 1
wcsd _ = 2
qwbh x = rsrf x * zlsn x
pbgp x = lbpj x + slcf x
rmfv _ = 7
mvfw _ = 13
cqjb _ = 3
zssv x = gjsm x * zfhg x
gnrz x = lqtl x * qccw x
qswg _ = 5
mwsl x = lzmh x + gfpj x
ljsl x = wfjl x * dwqm x
tsgz _ = 3
lmfh x = vzdd x + lzdh x
ntjs x = tbfz x * gpgc x
rlfd _ = 7
mdlg _ = 2
bdjr x = jhzw x + rswh x
blsf x = sswt x + vhtt x
wvts x = sgdf x * nbdv x
nggs x = dhgt x * zvrq x
rczv x = zddf x * wccf x
jjdz x = ltvg x * rvfg x
vwmh _ = 18
rgcc x = sqpl x * vjnb x
hzmt x = zpmp x `div` pcns x
rdnm _ = 5
ctgv x = njdf x * dtfv x
wbwc x = ztpb x * tzjn x
zvfc x = mnds x * jgrn x
mrsr x = cqjb x * wmtr x
zgpv _ = 7
ddsj x = dnmn x - thnm x
zcsh _ = 13
zfcp x = zqhh x - wrrz x
fgpj _ = 2
ltpq _ = 3
nljp x = jdqg x - gjfn x
ftrn _ = 2
qccw x = fzbz x + zdhl x
mvmw x = wjpm x - fsmr x
fspg x = wvpp x + jgzn x
wjbv x = mjzb x + gfcp x
ddpb _ = 6
bfws x = sqpm x * lscf x
ssrs _ = 2
svfw _ = 5
mcqm x = hlzd x + fhjp x
vfjc x = vpct x * tcch x
gvmp _ = 1
hfhj _ = 2
rrpb _ = 3
sptw _ = 6
jtrz x = rdlp x * lrlh x
qsjm _ = 7
gjdd x = rhwf x * rlgf x
grtw _ = 3
jlmg x = ljgq x `div` plcn x
wjgs x = lqnd x + vbll x
lfcb x = jtrz x + bptt x
nbrv _ = 1
zzjp _ = 5
gtvq _ = 2
whtw _ = 3
lnng _ = 4
qtqs _ = 8
zswv x = vbpt x - dzzz x
lglt _ = 5
lvqs x = nbfr x + mtrw x
lhjc _ = 5
zgpl x = mfpl x + clmh x
dnhj _ = 2
pzvv _ = 5
dszw _ = 2
cfvf x = nbvg x + crnr x
stfq x = grtg x - tprd x
qlvb x = htws x * cwtz x
zjsz _ = 3
qtjh x = wddn x * ppzg x
pjht x = mgmt x + rqzh x
pjcb x = mfdl x - mfvj x
ltlb x = pjfr x + mzdh x
csqd x = wbtp x + nbrv x
sscj _ = 3
qggb x = qpbd x * pzbn x
rdjq x = hghv x * ptww x
djtb x = smvs x + lgcn x
mtcj x = hbqf x * tqhv x
zlwm x = gpdc x * pjcb x
nsch _ = 2
ffww _ = 2
vnzb _ = 6
bsjq _ = 2
wwdn _ = 15
vzzj _ = 3
pzdh x = clhd x * gmlz x
mfwb x = stfq x `div` dmbc x
qlvz x = qpns x + sjhw x
gqds _ = 5
vhps _ = 10
ptgs x = fqlq x * bvgf x
wpft _ = 1
hdsh x = vljm x * ncgt x
tcvm x = qbhr x + lwcs x
qppm x = sfqj x * rgsd x
frrl _ = 2
pczb _ = 5
qggh x = hnfs x + zszc x
wwdw _ = 4
bhfw _ = 2
nmcn _ = 3
lnff _ = 6
tprd x = chhw x * rzjq x
gbpf _ = 2
ljzh x = bsfw x * cwlq x
zjbz _ = 3
smth _ = 2
nrjw x = jtsc x `div` ztnn x
hjpt _ = 5
qwqv x = pclz x `div` ssjd x
zmvg _ = 5
swbf x = jcwr x * drbf x
jcwr x = rsvn x `div` cfns x
bnfz _ = 1
dmpn x = qddm x + zfqt x
vmln x = zcnv x * nbsm x
jgmf _ = 5
pljb _ = 3
hmmm _ = 5
rjbf _ = 7
qzpq x = vmrh x `div` wsqt x
qcjf _ = 20
cwsz x = mdcp x * rdtv x
ljgq x = hpqn x + rpgs x
mdpg _ = 2
gmvw x = wwdc x - tgfz x
vbsb x = hwjt x * fjbp x
fhjp x = nfwg x * znwc x
hhgn _ = 4
dgbc x = gvln x * zwfh x
dmzq x = qmlp x * whsn x
nzdc x = dpcn x `div` vtjv x
wvmh x = ltqq x * rnqs x
ncnp _ = 15
vgsn _ = 3
nrqf x = nllc x * mmmn x
wqdj _ = 2
rshq x = fngm x * gqln x
jsmc x = nprp x * bfws x
gbhg x = pmlf x `div` prjf x
qlwn x = fcpf x + qsww x
rhwz x = lrqv x * pdzt x
rfpz x = bfbn x `div` qfsq x
jhzm x = ctbl x + lbls x
ccmh _ = 2
gjdv _ = 2
rzcw _ = 2
vrst x = wfsc x * fhgl x
svdd _ = 2
wpcg x = bqfs x * twmr x
nmcj x = drmn x * mqrh x
gffj x = hzrd x * gmgz x
fglw _ = 5
dnsj x = cwzb x * znzh x
mjmv x = sqrg x - dcfg x
bfwn _ = 3
dtht x = thwb x * prhr x
zfcd _ = 2
szpw _ = 7
hjfj x = swjj x * cqbc x
bvfb _ = 10
zqhh x = tpqn x * sdtc x
rwzn _ = 2
lmpm _ = 3
ccrc _ = 4
fwrt x = bstz x * gmmw x
phcs x = fhnp x * hmfn x
rjrr _ = 5
jcjv _ = 4
cprd _ = 4
wbgm _ = 4
nbdg x = lfdg x * bjbc x
tsbd _ = 1
qsnt _ = 11
ltqq _ = 20
mppt x = phhd x * nptp x
mqhh _ = 3
rffb x = rzzv x + cdql x
jdqg x = hggv x * wrvc x
vbch x = brpw x + plds x
rszm _ = 2
cnnq x = vpnm x + jrdq x
fqlq _ = 4
thnv _ = 5
fsgb _ = 2
ddfd _ = 11
hpvb _ = 5
gnqv _ = 2
qrfd _ = 5
rtnq _ = 2
lpnv _ = 9
hzng _ = 5
ssjt _ = 2
wvgc _ = 16
pbst x = vrjq x * mtgv x
ztqn _ = 4
bhlt _ = 2
htws _ = 2
dbmb _ = 2
lzmh x = llvc x + lgbp x
bstz x = pftl x + rhbb x
llmh _ = 14
trgc x = fgqr x + vswn x
shhz _ = 2
cjgz _ = 5
qvnh _ = 2
bglf _ = 5
bznr _ = 5
vpgc _ = 2
tztp _ = 2
bqwl _ = 3
cdhh _ = 3
wsgm _ = 7
plwg _ = 4
zfzt x = jpsj x * qngt x
mjhg x = sqnr x * prdf x
wrfl _ = 2
ffbh x = lswp x * tnbw x
mbqw _ = 5
vdmf _ = 4
mrtv _ = 12
gbfg x = gfcl x + mjwg x
jghl x = hfhj x * zhdt x
czss x = shpb x * lrrb x
vmzp x = rfpz x + vqfp x
fzjc _ = 16
grnt _ = 5
hwtj x = vbsb x + gcns x
jspj _ = 2
lrrb _ = 4
nwlz x = jsmc x `div` nsch x
tzwq _ = 4
sjhw x = hmmq x + bndm x
jmbc _ = 3
jfrj x = lrfl x * ddpb x
zwsb _ = 2
lrlh x = hctg x * zcdm x
rdlp x = lrrg x * pltr x
hdpg x = tpbr x * fzrr x
mtwm _ = 5
dpdl _ = 3
mwcn x = zffb x * ztqn x
rprr _ = 12
tbmq _ = 9
llrz _ = 14
pgsj x = pjmc x * ntrl x
dgpw _ = 5
nprv x = fgsb x + mmrz x
glvc _ = 20
dtfv x = bbsr x + wnnf x
jbrc _ = 8
wlbg x = dlqb x * bzwp x
fscs _ = 4
bjbc x = hqgb x + bltb x
nllh _ = 5
nwpn x = zssg x * gwnd x
pjzz _ = 2
rhct _ = 8
spcw x = svht x - tsmg x
dtzb x = gghf x * lcnp x
qnvd _ = 2
zjnq x = zrcw x * fwjv x
wnfq _ = 5
dgwg _ = 2
hvdb x = hqvc x * hlhs x
qlrb _ = 4
fhgb x = zzbs x * jvfq x
plvv _ = 12
dvbs x = mdfz x + qsnt x
mnhd x = fppd x * mfvg x
mcwm _ = 7
mdfz x = snzc x + spgl x
cbff x = znhc x + cvfr x
qcbz x = lzqz x + bdsw x
sqpl x = stpm x - bcjh x
jbzb _ = 2
vghc _ = 3
qtbj x = rjvr x - snlt x
pmqv _ = 5
csts x = bbtv x * zlgl x
scbr _ = 5
htfw x = dscf x + lqps x
lfdg _ = 5
tbbd x = cpcc x * htmg x
vtjv _ = 2
sgzd _ = 3
qhrf x = llpn x + jtgr x
dwzp _ = 11
dnmn x = nzln x * ndgg x
dmgh _ = 4
mmrz _ = 9
pzbn _ = 3
znwc _ = 2
plmf _ = 2
zdfc _ = 2
ssqm _ = 10
hbrv x = jlqz x * zhmg x
slfr x = wvtf x * ftzm x
qmwj x = jvcv x - rhzz x
lbqs x = nndt x + cdsd x
ltjc x = mrdl x * smcn x
vrgt x = zftn x * svff x
wnnf x = ndft x * dnsj x
dlbc _ = 10
snlt x = vmln x * ntdw x
lzqz x = lzwl x + lhjc x
qmbr x = zdcp x + qrjp x
zdcp x = lmsr x * svbz x
lmjb x = hjnc x * zhsp x
lqjd x = nzdz x + cgch x
hbnw _ = 15
thfl _ = 2
nndj _ = 11
rhtm _ = 9
pgjw x = wvsq x * thhw x
zrrl x = bmqf x * gwrm x
lzgs _ = 2
czbp x = zmrj x * mccf x
cgpm x = rhcb x * jwfc x
fgsb _ = 2
tsws x = pfvf x * ngpj x
qmln x = mpwv x * cccf x
lzrv x = qcch x + zrzd x
ltvg _ = 3
qqcl x = pvph x * dnqf x
svgq x = tthb x * qnnp x
cczr _ = 19
slcf x = nzsf x + zpdd x
vqgh x = bbbv x * qzpq x
hpmj x = hvzq x * wppr x
hsps _ = 2
cfns _ = 8
fvtm _ = 15
sfms _ = 8
sqnr _ = 2
tpml _ = 5
lcfr _ = 3
zfqs x = scrr x * ltlb x
qnqg _ = 5
pdjn x = fmmm x + znmw x
tmzv _ = 16
bczm x = frcf x + znqr x
dnzc _ = 17
jqlz _ = 2
bfbn x = twfq x * qrbc x
dcgw _ = 2
qvzb _ = 3
wlpf _ = 3
jsnt x = qvmm x * zbct x
zrcw x = nmqc x `div` wbdg x
gbfs _ = 2
dggc _ = 17
nbwm x = htfg x - pbst x
hlhs x = vcsf x + ldht x
mqrh _ = 3
jwrv x = slqz x + bpfj x
ptzw _ = 17
jpwc _ = 3
lrzf x = rgbn x + jhzm x
prgt x = nprv x + cfmc x
hngq x = jtrw x + gpzv x
tjww _ = 4
pntb x = mlhm x * ndbs x
ntdv x = qpmr x * mqwg x
lgzn x = ddzl x + hhgn x
mbcf _ = 10
qqdf _ = 10
tgfz x = jhqv x * bgmw x
qttq x = tjpn x - drjf x
njdg x = qggb x + fffr x
lrqv x = vvds x * vzvf x
mwgz x = cgpm x - chht x
vvds _ = 5
jqnj _ = 2
vwhr _ = 2
qqwp _ = 7
whsn x = vbsj x + scqn x
fhnp _ = 5
lmpw _ = 3
sgmj x = chzp x * hqnt x
rbwr _ = 5
trpn x = fhsb x + svgq x
hsbz _ = 2
sfsl _ = 3
lggn x = gjdd x `div` vnps x
rbmr x = ptgs x `div` hgqd x
tlcc x = lzdq x * wrqj x
gqjh x = tlgn x + hbzf x
sdbs x = crsz x * grbh x
nvdr _ = 10
fqss _ = 3
vgnr _ = 5
wrgt x = hbrv x + tngj x
jvcv x = lflw x * rfgs x
zbgw x = lzgs x * pqzh x
ftzm _ = 2
qnln _ = 3
rsqs x = fwrt x + qttq x
vdqc x = tqqg x - mbcf x
znrz _ = 3
rhzz _ = 3
tcrq _ = 3
mnsm x = fglw x * wgjz x
bjwv x = cvcd x `div` ttvq x
fsmr x = mrhs x - vghc x
lbzp _ = 3
scqn x = qtmd x * hmgl x
pdbj _ = 2
tlmc _ = 2
dfdq _ = 7
ggpz _ = 14
ngmb _ = 4
vwfs _ = 5
tdlh _ = 2
nrhb x = rprs x + rbmr x
hrmz _ = 2
rpgq x = cbcn x + fblh x
jqgn _ = 2
jpvz x = rtzc x * bqwl x
flnr x = jlrw x + vdzq x
wffd x = vznv x * ftdh x
dsff _ = 16
hzsg x = qdlz x - njdg x
qmbg _ = 2
dfgc x = nlrn x + stlw x
tdfv x = vhzt x + hfdd x
rsmz x = rrpb x * lpbc x
qnhv x = qqwp x * fdvt x
lrmb _ = 3
lzth _ = 12
fnvm x = ntjs x + frrv x
hzfs x = vzzj x + fbjf x
jvzj _ = 2
lrgg _ = 5
sljs _ = 5
gnlv x = qbhp x * psnd x
gspd _ = 19
wvsq _ = 2
qqtq x = bvfb x + rjbf x
bfvn x = brlh x - qplc x
sbdc x = jrps x * rqbr x
rgwv _ = 6
npcc x = whzd x + ghjz x
mgqm _ = 12
vznp x = hmpc x - fnww x
mvvm x = djbj x * wrfl x
qtbs _ = 2
gghf _ = 2
gjcg _ = 3
rlfn x = rrnq x * lhzs x
twrs _ = 3
bssq _ = 3
vblq x = qwgl x + nlnc x
sfqc _ = 3
wgth _ = 11
zwjl x = twrs x * sjgs x
dvqw x = nrhb x + lfcb x
ftdc _ = 9
nprp _ = 2
fwjv _ = 7
czbf _ = 3
brlh x = cbpj x * mvqj x
wczc _ = 4
zffb _ = 2
ngjt _ = 3
rhqz x = wqhm x * zfzt x
hjrg x = rqrd x - swrv x
cbbw _ = 2
dscf _ = 10
dftr _ = 2
qtfv x = ncjm x + nggs x
vpnm x = cwvh x * rbwr x
pcvq _ = 2
nqbq _ = 5
hnbl x = cldt x * qvgd x
jwff _ = 2
svrh _ = 5
fmvl _ = 5
dmhv x = mjhg x * sptw x
bgtd x = szvf x + svrh x
pzfd x = fczq x + mlfm x
vqmf _ = 2
ndft _ = 3
jlnl x = sqts x * zfmt x
rlvm x = rvpj x * zdfc x
mzcz x = qhfw x + rddv x
ttzn _ = 3
mgvl x = fsqh x + nnmp x
vjpt x = hjfj x `div` bhlt x
phhd x = lpgn x * jqhl x
ffdb x = lsmq x * qjwz x
cgch _ = 3
fvhj _ = 3
csrn x = hlgf x + hnlv x
qvtg x = qpcs x * wqdn x
wblh _ = 3
jtsl _ = 2
jppd x = lrmp x * qrfd x
lfrp x = jspj x * cflj x
bshh x = wggd x * jwff x
gqjl _ = 3
zssg _ = 11
fcjg x = wjlt x + vjpt x
ltjm _ = 3
prcf x = zldl x + bwjb x
snbg x = bzgj x - lngj x
csfj _ = 7
jltf _ = 5
shzd x = njmn x * znpz x
fvcj x = bmqm x * zgcl x
cmmv x = vwrn x + cscc x
fmnn _ = 13
vbll x = tsbd x + rprr x
frcf _ = 14
rpjz x = bfwn x * frjw x
bndm x = frnj x * tztv x
qtfw x = ndbv x * qpvc x
fppd _ = 3
nfmn x = njnm x - wtth x
crpb _ = 4
fnww _ = 1
cvnm _ = 20
jpzq x = fmnn x + vwmh x
tjrq _ = 2
fdvt x = cjsl x + zfwc x
gpwc x = csdw x * qnln x
zvdc x = wvch x * wblh x
gflj x = fvnl x + nrfj x
ptwq _ = 3
hdmr x = ttpj x * qtbj x
ndtf x = mvtz x * nhsv x
vcsf _ = 5
qljz _ = 2
bzwp x = nqbq x * pdcz x
hcmq x = nvbq x `div` gtjq x
msnt x = frjn x + mrtv x
nrqm x = jchm x * qsfj x
ptnn _ = 3
rhwf x = ddsj x + dgcw x
tthn x = wmbz x + djtb x
rwpn _ = 2
gwfr x = ptmp x + nzmw x
bggd x = gfht x * zdtr x
lbls _ = 4
gdmr _ = 5
mjzb x = mhgf x + zbgw x
wndm x = grzd x + mwjp x
prdf x = zzjp x * tddb x
rnhq x = dwpd x * cvhp x
tjjd x = strt x * ssrs x
vqnp x = wqgh x + jqnt x
mzrp x = jnpb x + jjdz x
zjpj _ = 1
lrdr _ = 4
lqnd _ = 3
bmcv _ = 9
fffr x = tccg x * jdhs x
mbcn _ = 2
qghm x = vfgr x + ltjm x
zzdv x = htfw x - jvfw x
psfm _ = 14
zszc _ = 8
qmwg x = hrpd x * qlwn x
dtwf _ = 2
zppj x = gghl x + jpqr x
rtzc x = nggq x * hhsz x
wvmq x = rlsm x + bslr x
ccmn x = qcrd x + mbrc x
hwwq x = wwnz x + qlvz x
snzc _ = 6
gbth _ = 2
zmwz x = ptrd x + fgdn x
hgcs x = gwhl x * nzjb x
cpcc _ = 2
ppzg _ = 5
thvd x = sfzt x * rfgf x
ctbl _ = 3
mjmb x = dfgc x + vrbn x
wccf _ = 2
dwbs x = wsgm x * nrdw x
fhzf x = lfmr x * vqmf x
znzh _ = 5
bcwc _ = 14
qhfw x = mnbf x * zzcm x
wczp _ = 16
rqjs x = smlf x + wjbl x
pzjl x = lpqq x * qlvb x
pbvp x = vpwt x - mgdt x
fncj x = thzh x + jlnl x
wggd x = jmvf x * vszp x
vrjq _ = 2
wbvb x = qwcj x * bqlr x
shzq _ = 2
gwvh x = pzjl x + wlsb x
mbhn _ = 4
htpb x = hgcs x + mvzq x
brpf _ = 5
wzgj x = ptnn x * gspd x
fhsb x = cgrp x * vpgc x
szvf x = zbsc x * jsps x
zjvq x = srlc x `div` zjqt x
szft x = dsvv x * fvqj x
hpsg x = tpcd x `div` tcqj x
zfqj x = dhbr x + mmvt x
pggm _ = 5
jcjn x = tcmm x + hjpt x
njss _ = 5
brzf _ = 5
nrtn x = ssjt x * zwrt x
dhbr x = wzzt x * hbnw x
rhbb _ = 9
gcrr _ = 4
mbpj x = vhwj x + fnvf x
mmww x = pgmm x * dlrc x
nrsl x = hclc x + ndrm x
wbhp x = wgvq x - hscr x
fwbl x = ffdb x - qmwj x
sfpj x = rjcb x * bddn x
wtms _ = 3
sdff x = vqnv x * wvmq x
bltg _ = 2
wfsc _ = 2
rrnq _ = 2
qfjb _ = 5
bbsr x = lfvc x + bqbd x
ndzr _ = 2
dwlg x = mbqw x * pvss x
tsvv x = nlrl x * bmcv x
jnzj x = cjqs x + dfss x
vdzq x = tptd x * mnsm x
wmbz x = dbvs x + bhtf x
hlcg x = fhdr x + sclr x
mngm _ = 7
rrzp _ = 2
rpmw _ = 2
mtgv x = qbnz x + tszn x
nrpn x = rsmz x + wznb x
sgfm x = sfqc x * qqtq x
sbqb x = gjwp x * hjmt x
twmr x = wjsm x + fnbq x
hhjd _ = 3
pdqv _ = 3
gmgz x = cqlc x - rpjz x
fgsf _ = 20
tnbw _ = 3
lrvh x = gpcm x * rbls x
dvfs x = jbpl x + jzzl x
bcjh x = wwdw x + vzjm x
wbdg _ = 2
wwnz x = snnv x * csrn x
lmsr _ = 11
bcfl x = cbvr x + mzrp x
npjd x = ldlh x + dthv x
bzff x = zwsf x * nrpn x
tqfr _ = 2
njdf _ = 3
cztm x = csfj x * trrs x
cgrp _ = 8
gfht x = fcjg x * cbdc x
bsfw _ = 8
pcjh x = ptnl x + rcfj x
bcbj _ = 17
dbcj _ = 2
dfpv _ = 11
pptc x = ncfg x + gbfg x
hjmt _ = 4
pggh x = tlvh x + tczp x
cbpj _ = 2
pfvf _ = 14
qwcj _ = 2
qnqf _ = 3
stpm x = pjzz x * ljfg x
zgjr _ = 9
wqdd x = grmj x * wbgm x
rvql x = nfqb x * hfjf x
pdrr _ = 2
gjsm x = jrpq x * trth x
hwjt x = pgsj x + nlvg x
rhcb _ = 2
